webtalk_init -webtalk_dir /home/akayashima/H31_Xilinx/chardisp/chardisp.sim/chardisp_sim/chardisp_sim.sim/sim_1/behav/xsim/xsim.dir/tb_chardisp_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Apr 18 16:58:38 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211387882_1777527812_210663870_969" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "8cf7803e-613c-4585-b6c4-d02f728ae680" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c04a04d4c56a4f8c993d67d2afccd03d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "CentOS" -context "user_environment"
webtalk_add_data -client project -key os_release -value "CentOS Linux release 7.5.1804 (Core)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4073.071 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "134628_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3520956756 -regid "211387882_1777527812_210663870_969" -xml /home/akayashima/H31_Xilinx/chardisp/chardisp.sim/chardisp_sim/chardisp_sim.sim/sim_1/behav/xsim/xsim.dir/tb_chardisp_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/akayashima/H31_Xilinx/chardisp/chardisp.sim/chardisp_sim/chardisp_sim.sim/sim_1/behav/xsim/xsim.dir/tb_chardisp_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/akayashima/H31_Xilinx/chardisp/chardisp.sim/chardisp_sim/chardisp_sim.sim/sim_1/behav/xsim/xsim.dir/tb_chardisp_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
