# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/akayashima/H31_Xilinx/chardisp/chardisp_ip/src/CGROM/CGROM.xci
# IP: The module: 'CGROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/akayashima/H31_Xilinx/chardisp/chardisp_ip/src/CGROM/CGROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CGROM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/akayashima/H31_Xilinx/chardisp/chardisp_ip/src/CGROM/CGROM.xci
# IP: The module: 'CGROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/akayashima/H31_Xilinx/chardisp/chardisp_ip/src/CGROM/CGROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CGROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
