# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param project.hsv.suppressChildGraphs 0
create_project -in_memory -part xc7a200tsbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/akayashima/H31_Xilinx/chardisp/chardisp.tmp/edit_ip_project.cache/wt [current_project]
set_property parent.project_path /home/akayashima/H31_Xilinx/chardisp/chardisp.tmp/edit_ip_project.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys_video:part0:1.1 [current_project]
set_property ip_repo_paths /home/akayashima/H31_Xilinx/chardisp/chardisp_ip [current_project]
set_property ip_output_repo /home/akayashima/H31_Xilinx/chardisp/chardisp.tmp/edit_ip_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/akayashima/H31_Xilinx/chardisp/chardisp_ip/ROMDATA/CGDATA.coe
read_verilog /home/akayashima/H31_Xilinx/chardisp/chardisp_ip/vga_param.vh
read_verilog -library xil_defaultlib {
  /home/akayashima/H31_Xilinx/chardisp/chardisp_ip/chardisp.v
  /home/akayashima/H31_Xilinx/chardisp/chardisp_ip/chardisp_v1_0_S00_AXI.v
  /home/akayashima/H31_Xilinx/chardisp/chardisp_ip/pckgen.v
  /home/akayashima/H31_Xilinx/chardisp/chardisp_ip/syncgen.v
  /home/akayashima/H31_Xilinx/chardisp/chardisp_ip/chardisp_v1_0.v
}
read_ip -quiet /home/akayashima/H31_Xilinx/chardisp/chardisp_ip/src/CGROM/CGROM.xci
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/chardisp/chardisp_ip/src/CGROM/CGROM_ooc.xdc]

read_ip -quiet /home/akayashima/H31_Xilinx/chardisp/chardisp_ip/src/VRAM/VRAM.xci
set_property used_in_implementation false [get_files -all /home/akayashima/H31_Xilinx/chardisp/chardisp_ip/src/VRAM/VRAM_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top chardisp_v1_0 -part xc7a200tsbg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef chardisp_v1_0.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file chardisp_v1_0_utilization_synth.rpt -pb chardisp_v1_0_utilization_synth.pb"
